version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
